### ISSUE TITLE
Titanium SDK 9.0.0.GA Android build error

### ISSUE THREAD

**Issue by michielvaneerd** [Scandit/barcodescanner-sdk-titanium-samples#17]
When I try to build my Titanium app with your Scandit Titanium module for Android, I get the following error:

```
[INFO]  [GRADLE] > Task :app:transformClassesWithMultidexlistForDebug FAILED
[ERROR] [GRADLE] D8: Program type already present: com.mirasense.scanditsdk.BuildConfig
[ERROR] [GRADLE] 
[ERROR] [GRADLE] FAILURE: Build failed with an exception.
[ERROR] [GRADLE] 
[ERROR] [GRADLE] * What went wrong:
[ERROR] [GRADLE] Execution failed for task ':app:transformClassesWithMultidexlistForDebug'.
[ERROR] [GRADLE] > com.android.build.api.transform.TransformException: Error while generating the main dex list:
[ERROR] [GRADLE]   Error while merging dex archives: 
[ERROR] [GRADLE]   Learn how to resolve the issue at https://developer.android.com/studio/build/dependencies#duplicate_classes.
[ERROR] [GRADLE]   Program type already present: com.mirasense.scanditsdk.BuildConfig
```

I'm using: Titanium SDK 9.0.0.GA
Scandit Android module 5.14.4

When I'm building with the previous Titanium version (8.3.1.GA) everything is OK.

**Comment by petradonka** [comment]
Hi @michielvaneerd,

Unfortunately, we haven't had a chance yet to look at Titanium 9.0.0 since it was released.
Please reach out to support@scandit.com, they'll be able to help you better with this issue.

Cheers,
Petra

**Comment by jerry42** [comment]
Hello,

I have the same problem did you manage to work something out @michielvaneerd ?

Cheers

**Comment by ScanditSupport** [comment]
@jerry42 we started working on a Titanium 9.0.0 compatible version and it will include the update to the latest 6.x API version as well as the latest improvements.
Due to the significant changes, we're not able to confirm a final release date. But as Petra mentioned, you may want to reach out to support@scandit.com an such that we can keep you up to date.

**Comment by jerry42** [comment]
Ok great ! Thanks for your reply. I will keep an eye open and use Titanium 8.3.0 in the meanwhile.

Thanks again.

**Comment by brentonhouse** [comment]
@jerry42 @ScanditSupport @michielvaneerd  

I work for Axway (maker of Titanium Mobile).  One of our engineers figured out that the latest module just had the wrong Xcode command attached to it inside the zip file.  It’s a simple change and doesn’t require a recompile from the Scandit team.  With that change, it now works with the 9.x SDKs. 

I can post the changes we made here for others.

**Comment by ScanditSupport** [comment]
@brentonhouse Thanks for your comment and the investigation you and your team have been doing. 
We are happy to verify the changes and check whether we can adapt our packages to make the 5.x version compatible. 

I'll reach out to you directly.
@jerry42 would you mind reaching out to us via the above mentioned support email? Just to make sure we can support you best and keep you up to date.

**Comment by jerry42** [comment]
Thanks for your answers and support. I have just sent an email to support@scandit.com

**Comment by ScanditSupport** [comment]
@michielvaneerd  @jerry42 
Hi both, 
we've release Scandit Datacapture SDK 6.8 which supports Titanium 9.3.0GA 
Please find the release notes [here](https://docs.scandit.com/data-capture-sdk/titanium/release-notes/6.8.html).

In case you have further question, please reach out to us directly via 
https://support.scandit.com/hc/en-us/requests/new 

Best regards
Scandit Support
