### ISSUE TITLE
ScandIt iOS SDK modules not working with Titanium SDK 9.x

### ISSUE THREAD

**Issue by brentonhouse** [Scandit/barcodescanner-sdk-titanium-samples#18]
Getting errors when using using the Scandit iOS SDK modules with Titanium SDK 9.x.  

I believe the SDK just needs to be rebuilt with the `x86_64` architecture (which is missing in current build)

https://wiki.appcelerator.org/display/guides2/iOS+Module+64-bit+Support#iOSModule64-bitSupport-Undefinedsymbolsforarchitecture

**Comment by brentonhouse** [comment]
Also getting this when trying to build to device:

```
[TRACE] Undefined symbols for architecture arm64:
[TRACE]   "_OBJC_CLASS_$_MLModelConfiguration", referenced from:
[TRACE]       objc-class-ref in ScanditBarcodeScanner(scandit-barcodescanner.o)
[TRACE]   "_OBJC_CLASS_$_MLModel", referenced from:
[TRACE]       objc-class-ref in ScanditBarcodeScanner(scandit-barcodescanner.o)
[TRACE]   "_OBJC_CLASS_$_MLDictionaryFeatureProvider", referenced from:
[TRACE]       objc-class-ref in ScanditBarcodeScanner(scandit-barcodescanner.o)
[TRACE]   "_OBJC_CLASS_$_MLFeatureValue", referenced from:
[TRACE]       objc-class-ref in ScanditBarcodeScanner(scandit-barcodescanner.o)
[TRACE]   "_OBJC_CLASS_$_MLMultiArray", referenced from:
[TRACE]       objc-class-ref in ScanditBarcodeScanner(scandit-barcodescanner.o)
[TRACE] ld: symbol(s) not found for architecture arm64
[TRACE] clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by ScanditSupport** [comment]
@brentonhouse the current version of the SDK is for Titanium SDK 8.x and may produce above errors when used with Titanium SDK 9.x

If you reach out to Scandit Support directly, we are able to notify you once the compatible version of the Scandit SDK is available:
https://support.scandit.com/hc/en-us/requests/new 

Thanks and best regards
Scandit Support Team
